 # A static site
services:
  - type: web
    name: frontend
    env: static
    rootDir: ./frontend
    buildCommand: yarn build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: https://backend.onrender.com
      - type: rewrite
        source: /api
        destination: /index.html
    envVars:
      - key: REACT_API_URL
        fromService: 
          type: web
          name: backend
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: backend
    env: node
    rootDir: ./backend
    buildCommand: yarn
    startCommand: yarn start