 # A static site
services:
  - type: web
    name: frontend
    env: static
    rootDir: ./frontend
    buildCommand: yarn build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html